"use client";
import {useEffect,useState} from "react";
type Person={id:string;name:string;position:string;role:"Founder"|"Contributor";kind:string;active:boolean};
type Position={id:string;title:string;workstream:string;access:string};
type Task={id:string;title:string;owner:string;stream:string;status:string;objective:string;output:string;authority:string;context:string};
type Opportunity={id:string;name:string;type:string;stage:string;owner:string;next:string};
type Store={people:Person[];positions:Position[];tasks:Task[];opps:Opportunity[];activity:string[]};
const initial:Store={
 people:[
 {id:"USR-001",name:"Founder",position:"Founder & Protocol Architect",role:"Founder",kind:"Founder",active:true},
 {id:"USR-002",name:"Josh",position:"Positioning & Communications Contributor",role:"Contributor",kind:"Volunteer",active:true},
 {id:"USR-003",name:"Abhyagata Magistrani",position:"Strategic Partnerships & External Relations Contributor",role:"Contributor",kind:"Volunteer",active:true},
 {id:"USR-004",name:"Irma Dewi Astriyani",position:"Provider & Commercial Operations Contributor",role:"Contributor",kind:"Volunteer",active:true},
 {id:"USR-TEST-001",name:"VYREN Internal Test",position:"Internal Operations & QA Contributor",role:"Contributor",kind:"TEST ONLY",active:true}
 ],
 positions:[
 {id:"POS-001",title:"Founder & Protocol Architect",workstream:"Founder Review",access:"Founder"},
 {id:"POS-002",title:"Positioning & Communications Contributor",workstream:"Communications & Positioning",access:"Contributor"},
 {id:"POS-003",title:"Strategic Partnerships & External Relations Contributor",workstream:"Partnerships & Funding",access:"Contributor"},
 {id:"POS-004",title:"Provider & Commercial Operations Contributor",workstream:"Provider & Commercial Operations",access:"Contributor"},
 {id:"POS-TEST-001",title:"Internal Operations & QA Contributor",workstream:"Operations / Admin",access:"Contributor"}
 ],
 tasks:[{id:"TEST-001",title:"Validate contributor task workflow",owner:"USR-TEST-001",stream:"Operations / Admin",status:"BRIEFED",objective:"Test assignment, acceptance, submission and Founder review",output:"Documented QA observations",authority:"May research and report; no sign, funds, binding commitments or canonical changes",context:"GNR-STD-001 v1.3 (read-only)"}],
 opps:[],activity:["Demo initialized. All data is simulated."]
};
const NAV=["Home","My Work","Workstreams","Opportunities","Genesis Readiness","Reviews","Team","Project Context","Reports","Settings"];
const STAGES=["BACKLOG","BRIEFED","ACCEPTED","IN PROGRESS","WAITING EXTERNAL","FOUNDER REVIEW","BLOCKED","COMPLETED","CANCELLED","SUPERSEDED"];
const STREAMS=["Communications & Positioning","Partnerships & Funding","Provider & Commercial Operations","Genesis Readiness","Founder Review","Operations / Admin"];
export default function Page(){
 const [store,setStore]=useState<Store>(initial);const [ready,setReady]=useState(false);
 const [page,setPage]=useState("Home");const [actor,setActor]=useState("USR-001");const [modal,setModal]=useState("");const [name,setName]=useState("");const [extra,setExtra]=useState("");const [pick,setPick]=useState("");const [selected,setSelected]=useState("TEST-001");
 useEffect(()=>{try{const raw=localStorage.getItem("vyrencc-mvp-demo-v1");if(raw){const parsed=JSON.parse(raw);if(parsed?.people&&parsed?.tasks&&parsed?.positions&&parsed?.opps)setStore(parsed)}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("vyrencc-mvp-demo-v1",JSON.stringify(store))},[ready,store]);
 const founder=actor==="USR-001";const current=store.people.find(p=>p.id===actor)??store.people[0];
 const mine=store.tasks.filter(t=>t.owner===actor);const visible=founder?store.tasks:mine;
 const update=(fn:(s:Store)=>Store,event:string)=>setStore(s=>{const x=fn(s);return {...x,activity:[event,...x.activity].slice(0,70)}});
 const status=(t:Task,next:string)=>{if(!founder && !(t.owner===actor && ((t.status==="BRIEFED" && next==="ACCEPTED")||(t.status==="ACCEPTED" && next==="IN PROGRESS")||(t.status==="IN PROGRESS"&&next==="FOUNDER REVIEW"))))return;update(s=>({...s,tasks:s.tasks.map(z=>z.id===t.id?{...z,status:next}:z)}),t.id+" moved to "+next)};
 const create=()=>{
  if(!founder||!name.trim())return;
  if(modal==="person"){const pos=store.positions.find(p=>p.id===pick)||store.positions[1];const id="USR-"+Date.now();update(s=>({...s,people:[...s.people,{id,name:name.trim(),position:pos.title,role:"Contributor",kind:"TEST ONLY / NOT INVITED",active:true}]}),"New simulated person: "+name)}
  if(modal==="position"){const id="POS-"+Date.now();update(s=>({...s,positions:[...s.positions,{id,title:name.trim(),workstream:pick||STREAMS[5],access:"Contributor"}]}),"Position created: "+name)}
  if(modal==="task"){const id="TEST-"+Date.now();update(s=>({...s,tasks:[...s.tasks,{id,title:name.trim(),owner:pick||"USR-TEST-001",stream:STREAMS[5],status:"BRIEFED",objective:extra||"Example test objective",output:"Submitted report",authority:"Research and report only. No commitments.",context:"Canonical references read-only"}]}),"Demo task created: "+name)}
  if(modal==="opportunity"){const id="OPP-"+Date.now();update(s=>({...s,opps:[...s.opps,{id,name:name.trim(),type:"Partnership",stage:"Research",owner:pick||"USR-003",next:extra||"Research and qualify"}]}),"Demo opportunity created: "+name)}
  setModal("");setName("");setPick("");setExtra("");
 };
 const launch=(m:string)=>{setName("");setExtra("");setPick(m==="position"?STREAMS[5]:m==="person"?store.positions[4]?.id:m==="opportunity"?"USR-003":"USR-TEST-001");setModal(m)};
 const taskcard=(t:Task)=><div key={t.id} className="card stack"><div className="row between"><b>{t.title}</b><span className={"badge "+(t.status==="COMPLETED"?"good":t.status==="FOUNDER REVIEW"?"warn":"")}>{t.status}</span></div><span className="small muted">{t.id} · {t.stream} · {store.people.find(p=>p.id===t.owner)?.name}</span><p>{t.objective}</p><p className="small muted">Output: {t.output}</p><p className="small muted">Boundaries: {t.authority}</p><div className="row"><button onClick={()=>setSelected(selected===t.id?"":t.id)}>{selected===t.id?"Hide details":"Details"}</button>{t.status==="BRIEFED"&&t.owner===actor&&<button onClick={()=>status(t,"ACCEPTED")}>Accept</button>}{t.status==="ACCEPTED"&&t.owner===actor&&<button onClick={()=>status(t,"IN PROGRESS")}>Start</button>}{t.status==="IN PROGRESS"&&t.owner===actor&&<button onClick={()=>status(t,"FOUNDER REVIEW")}>Submit</button>}{founder&&t.status==="FOUNDER REVIEW"&&<><button onClick={()=>status(t,"COMPLETED")}>Accept result</button><button onClick={()=>status(t,"IN PROGRESS")}>Request revision</button></>}</div>{selected===t.id&&<div className="alert small">Canonical context: {t.context}. This demo cannot change lifecycle authority, economic rights or VDCP acceptance.</div>}</div>;
 return <div className="shell"><aside className="side"><div className="brand">◈ VYREN</div><div className="small muted">COMMAND CENTER · DEMO</div><nav className="nav">{NAV.filter(n=>founder||!["Reviews","Settings"].includes(n)).map(n=><button key={n} className={page===n?"active":""} onClick={()=>setPage(n)}>{n}</button>)}</nav><div className="footer">PREVIEW · LOCAL DEMO DATA<br/>Not canonical · No real accounts</div></aside><main className="main"><header className="top"><div><h1>{page}</h1><p className="muted small">Execution workspace · v0.1 preview</p></div><div className="row"><label className="small muted">View as <select value={actor} onChange={e=>{setActor(e.target.value);setPage(e.target.value==="USR-001"?"Home":"My Work")}}>{store.people.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div></header><div className="alert" style={{marginBottom:18}}>SIMULATED USER VIEW. There is no authentication or server authorization here. Do not enter secrets or use this preview for real assignments.</div>
 {page==="Home"&&<><div className="grid">{[["Active Tasks",store.tasks.filter(t=>!["COMPLETED","CANCELLED","SUPERSEDED"].includes(t.status)).length],["Waiting External",store.tasks.filter(t=>t.status==="WAITING EXTERNAL").length],["Founder Review",store.tasks.filter(t=>t.status==="FOUNDER REVIEW").length],["Team Members",store.people.length]].map(([label,n])=><div className="panel" key={label}><p className="muted">{label}</p><div className="metric">{n}</div></div>)}</div><div className="two"><section className="panel"><div className="sectionTitle"><h2>Priority tasks</h2><button onClick={()=>setPage("My Work")}>Open work</button></div><div className="list">{visible.map(taskcard)}</div></section><section className="panel"><h2>Execution lanes</h2><div className="list">{STREAMS.map(x=><div className="item" key={x}>{x}</div>)}</div></section></div></>}
 {page==="My Work"&&<section className="panel"><div className="sectionTitle"><h2>{founder?"All assigned work":"My assignments"}</h2>{founder&&<button className="primary" onClick={()=>launch("task")}>+ New Task</button>}</div><div className="stack">{visible.length?visible.map(taskcard):<p className="muted">No tasks assigned.</p>}</div></section>}
 {page==="Workstreams"&&<div className="grid">{STREAMS.map(stream=><div className="panel" key={stream}><h3>{stream}</h3><p className="muted small">{visible.filter(t=>t.stream===stream).length} visible tasks</p><div className="stack" style={{marginTop:12}}>{visible.filter(t=>t.stream===stream).map(taskcard)}</div></div>)}</div>}
 {page==="Opportunities"&&<section className="panel"><div className="sectionTitle"><h2>Opportunity pipeline</h2>{founder&&<button onClick={()=>launch("opportunity")}>+ Add Opportunity</button>}</div><p className="muted small">No fabricated live provider records. Create demonstration opportunities for testing.</p><div className="grid" style={{marginTop:14}}>{["Research","Qualified","Contacted","Reply Received","Discussion","Proposal","Internal Review","Accepted","Rejected","Dormant"].map(stage=><div className="card" key={stage}><h3>{stage}</h3>{store.opps.filter(o=>o.stage===stage&&(founder||o.owner===actor)).map(o=><div className="item" key={o.id}><b>{o.name}</b><p className="small muted">{o.type} · {o.next}</p><select value={o.stage} disabled={!founder} onChange={e=>update(s=>({...s,opps:s.opps.map(q=>q.id===o.id?{...q,stage:e.target.value}:q)}),o.id+" changed stage")}>{["Research","Qualified","Contacted","Reply Received","Discussion","Proposal","Internal Review","Accepted","Rejected","Dormant"].map(st=><option key={st}>{st}</option>)}</select></div>)}</div>)}</div></section>}
 {page==="Genesis Readiness"&&<><div className="alert">Lifecycle reference: PRE-GENESIS (historical control context, not a live gate signal). No checklist score without verified, applicable evidence.</div><div className="grid" style={{marginTop:14}}>{["Audience / Awareness","Communications","Partnerships","Funding / Resources","Provider / Safeguarding","Legal / Offeror","Security","Operations","Participant Flow","Evidence / Production"].map(x=><div className="panel" key={x}><h3>{x}</h3><p className="muted small">NOT ASSESSED · No verified evidence in demo</p></div>)}</div></>}
 {page==="Reviews"&&founder&&<section className="panel"><h2>Founder review queue</h2><div className="stack" style={{marginTop:14}}>{store.tasks.filter(t=>t.status==="FOUNDER REVIEW").map(taskcard)}{!store.tasks.some(t=>t.status==="FOUNDER REVIEW")&&<p className="muted">No submitted tasks.</p>}</div></section>}
 {page==="Team"&&<><section className="panel"><div className="sectionTitle"><h2>People</h2>{founder&&<button className="primary" onClick={()=>launch("person")}>+ Add Person</button>}</div><div className="tablewrap"><table><thead><tr><th>Name</th><th>Position</th><th>Engagement</th><th>Status</th></tr></thead><tbody>{store.people.filter(p=>founder||p.id===actor).map(p=><tr key={p.id}><td>{p.name}</td><td>{p.position}</td><td>{p.kind}</td><td>{p.active?"Active (demo)":"Archived"}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="sectionTitle"><h2>Positions</h2>{founder&&<button onClick={()=>launch("position")}>+ New Position</button>}</div><div className="tablewrap"><table><thead><tr><th>ID</th><th>Position</th><th>Workstream</th><th>Role</th></tr></thead><tbody>{store.positions.map(p=><tr key={p.id}><td className="small muted">{p.id}</td><td>{p.title}</td><td>{p.workstream}</td><td>{p.access}</td></tr>)}</tbody></table></div></section></>}
 {page==="Project Context"&&<section className="panel stack"><h2>Read-only canonical registry</h2><p>Rev4.6 locked core · Lifecycle Decision Ledger LC-01 to LC-39 · GNR-STD-001 v1.3.</p><div className="alert">No canonical write, lifecycle gate approval, settlement, or governance authority is exposed by this application.</div></section>}
 {page==="Reports"&&<section className="panel"><h2>Demo activity</h2><div className="list">{store.activity.map((x,i)=><div className="item" key={i}>{x}</div>)}</div></section>}
 {page==="Settings"&&founder&&<section className="panel stack"><h2>Founder workspace settings</h2><p>Team configuration and data portability (preview only).</p><div className="row"><button onClick={()=>{const blob=new Blob([JSON.stringify(store,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="vyren-command-center-demo.json";a.click();URL.revokeObjectURL(url)}}>Export demo JSON</button><button onClick={()=>{if(window.confirm("Reset all browser demo data?")){setStore(initial);setPage("Home")}}}>Reset demo records</button></div><p className="small muted">Production settings, real user invites, authentication and access control are NOT implemented.</p></section>}
 </main>{modal&&founder&&<><div className="backdrop" onClick={()=>setModal("")}/><aside className="drawer stack"><div className="sectionTitle"><h2>{modal==="person"?"Add simulated person":modal==="position"?"Create position":modal==="task"?"Create test task":"Create test opportunity"}</h2><button onClick={()=>setModal("")}>Close</button></div><div className="field"><label>{modal==="person"?"Person name":modal==="position"?"Position title":modal==="task"?"Task title":"Opportunity name"}</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Enter display name"/></div><div className="field"><label>{modal==="person"?"Assign position":modal==="position"?"Workstream":modal==="task"?"Owner":"Opportunity owner"}</label><select value={pick} onChange={e=>setPick(e.target.value)}>{(modal==="position"?STREAMS:modal==="person"?store.positions.map(p=>p.id):store.people.filter(p=>p.role==="Contributor").map(p=>p.id)).map(v=><option key={v} value={v}>{modal==="person"?store.positions.find(p=>p.id===v)?.title:modal==="position"?v:store.people.find(p=>p.id===v)?.name}</option>)}</select></div>{(modal==="task"||modal==="opportunity")&&<div className="field"><label>{modal==="task"?"Objective":"Next action"}</label><textarea rows={3} value={extra} onChange={e=>setExtra(e.target.value)}/></div>}<div className="alert small">This only changes browser demo data. No invite, external communication or real account is created.</div><button className="primary" onClick={create} disabled={!name.trim()}>Save demo record</button></aside></>}</div>
}